Repository SwadRatna/swadratna_admin_app, pull requests merged in 2025-09, with the labels that each got.

#1 Base Hilt Setup for the project.
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swadratna/swadratna_admin/MainActivity.kt
  app/src/main/java/com/swadratna/swadratna_admin/SwadRatnaApplication.kt
  app/src/main/java/com/swadratna/swadratna_admin/base/BaseViewModel.kt
  app/src/main/java/com/swadratna/swadratna_admin/data/repository/Repository.kt
  app/src/main/java/com/swadratna/swadratna_admin/di/NetworkModule.kt
  app/src/main/java/com/swadratna/swadratna_admin/di/RepositoryModule.kt
  app/src/main/java/com/swadratna/swadratna_admin/navigation/NavGraph.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/components/BottomNavBar.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/dashboard/DashboardScreen.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/dashboard/DashboardViewModel.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/home/HomeScreen.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/home/HomeViewModel.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/theme/Color.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/theme/Theme.kt
  gradle/libs.versions.toml
Labels: enhancement

#2 Base Setup for Project
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swadratna/swadratna_admin/MainActivity.kt
  app/src/main/java/com/swadratna/swadratna_admin/SwadRatnaApplication.kt
  app/src/main/java/com/swadratna/swadratna_admin/base/BaseViewModel.kt
  app/src/main/java/com/swadratna/swadratna_admin/data/repository/Repository.kt
  app/src/main/java/com/swadratna/swadratna_admin/di/NetworkModule.kt
  app/src/main/java/com/swadratna/swadratna_admin/di/RepositoryModule.kt
  app/src/main/java/com/swadratna/swadratna_admin/navigation/NavGraph.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/components/BottomNavBar.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/dashboard/DashboardScreen.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/dashboard/DashboardViewModel.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/home/HomeScreen.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/home/HomeViewModel.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/theme/Color.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/theme/Theme.kt
  gradle/libs.versions.toml
Labels: setup

#3 Base UI setup with edge-to-edge handling.
  app/src/main/java/com/swadratna/swadratna_admin/MainActivity.kt
  app/src/main/java/com/swadratna/swadratna_admin/navigation/NavGraph.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/components/BottomNavBar.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/dashboard/DashboardScreen.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/dashboard/DashboardViewModel.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/theme/Theme.kt
  app/src/main/res/drawable/ic_analytics.xml
  app/src/main/res/drawable/ic_campaign.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_store.xml
Labels: enhancement

#5 Handle Store Management flow
  app/src/main/java/com/swadratna/swadratna_admin/model/Store.kt
  app/src/main/java/com/swadratna/swadratna_admin/navigation/NavGraph.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/campaign/CampaignViewModel.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/components/BottomNavBar.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/components/EmptyStateMessage.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/components/LoadingIndicator.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/dashboard/DashboardScreen.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/settings/SettingsScreen.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/store/CreateStoreScreen.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/store/StoreScreen.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/store/StoreViewModel.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/store/components/StoreItem.kt
  app/src/main/java/com/swadratna/swadratna_admin/utils/SharedPrefsManager.kt
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_logout.xml
  gradle/libs.versions.toml
Labels: enhancement, flow

#13 Menu Management screen
  app/build.gradle.kts
  app/src/main/java/com/swadratna/swadratna_admin/data/model/MenuItem.kt
  app/src/main/java/com/swadratna/swadratna_admin/data/remote/MenuItemDto.kt
  app/src/main/java/com/swadratna/swadratna_admin/data/remote/api/MenuApi.kt
  app/src/main/java/com/swadratna/swadratna_admin/data/repository/MenuRepository.kt
  app/src/main/java/com/swadratna/swadratna_admin/di/NetworkModule.kt
  app/src/main/java/com/swadratna/swadratna_admin/navigation/NavGraph.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/menu/MenuScreen.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/menu/MenuUiState.kt
  app/src/main/java/com/swadratna/swadratna_admin/ui/menu/MenuViewModel.kt
  gradle/libs.versions.toml
Labels: enhancement, flow
